name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NAME: 'Ber Demo'
  ENV_FILE_CONTENTS: ${{ secrets.ENV_FILE_CONTENTS }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my_work_dir

    steps:
    - name: Print env variables
      run: echo "Env variables $ENV_FILE_CONTENTS"
    - name: Env file
      run: echo "Some text" > .env
    - name: Print .env file contents
      run: cat .env
    - name: Wait for .env file
      run: sleep 2
    - name: Upload .env file
      uses: actions/upload-artifact@v3
      with:
        name: env-file
        path: ${{ github.workspace }}/.env
    - uses: actions/checkout@v3
    - name: Generate deploment package
      run: zip -r deploy.zip . -x '*.git*' .env
    - name: Upload deployment package
      uses: actions/upload-artifact@v3
      with:
        name: deploy-package
        path: deploy.zip
    - name: Create file
      run: | 
        touch .env2 
        echo "Some text for env2" >> .env2
        cat .env2
    - name: Upload env2
      uses: actions/upload-artifact@v3
      with:
        name: env2-package
        path: my_work_dir/.env2
