name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NAME: 'Ber Demo'
  ENV_FILE_CONTENTS: ${{ secrets.ENV_FILE_CONTENTS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print env variables
      run: echo "Env variables $ENV_FILE_CONTENTS"
    - name: Env file 0
      run: |
        mkdir -p ~/new/artifact
        echo "Some text!!" > ~/new/artifact/env
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifacts
        path: ~/new/**/*
    - name: Env file
      run: echo "Some text!" > env2
    - name: Print .env file contents
      run: cat env2
    - name: Upload .env file
      uses: actions/upload-artifact@v4
      with:
        name: env-file
        path: env2
    - uses: actions/checkout@v3
    - name: View files
      run: ls -a .
    - name: Generate deploment package
      run: zip -r deploy.zip . -x '*.git*'
    - name: Upload deployment package
      uses: actions/upload-artifact@v3
      with:
        name: deploy-package
        path: deploy.zip
    - name: Env file
      run: echo "Some text BE1" > ${{ github.workspace }}/.env
    - name: Print .env file contents
      run: cat ${{ github.workspace }}/.env
    - name: Find .env file
      id: find_env
      run: |
        env_file=$(find ${{ github.workspace }} -name ".env" -type f)
        echo "::set-output name=env_file::$env_file"
    - name: Upload .env file
      uses: actions/upload-artifact@v3
      with:
        name: env-file
        path: ${{ steps.find_env.outputs.env_file }}
    
