name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  NAME: 'Ber Demo'
  ENV_FILE_CONTENTS: ${{ secrets.ENV_FILE_CONTENTS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Env file
      run: echo "$ENV_FILE_CONTENTS" > .env
    - uses: actions/checkout@v3
    - name: Generate deploment package
      run: zip -r deploy.zip . -x '*.git*' .env
    - name: Upload deployment package
      uses: actions/upload-artifact@v2
      with:
        name: deploy-package
        path: deploy.zip
